name: CI

on:
  push:
    branches:
      - main
    tags: '*'

  pull_request:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: {% raw %}${{ github.workflow }}-${{ github.ref }}{% endraw %}
  cancel-in-progress: {% raw %}${{ startsWith(github.ref, 'refs/pull/') }}{% endraw %}

jobs:
  run-tests:
    name: Julia {% raw %}${{ matrix.version }} (${{ matrix.os }}, ${{ matrix.arch }}){% endraw %}

    strategy:
      fail-fast: false

      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        arch: [x64{% if cookiecutter.ci_include_x86 == "yes" %}, x86{% endif %}]
        version: ['1.7', '1.8', '1.9']
{% if cookiecutter.ci_include_x86 == "yes" %}
        exclude:
          - os: macos-latest
            arch: x86
{% endif %}
    runs-on: {% raw %}${{ matrix.os }}{% endraw %}
{% if cookiecutter.ci_include_codecov == "yes" %}
    env:
        codecov-os: 'Linux'
        codecov-arch: x64
        codecov-version: '1.9'
{% endif %}
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Julia environment
        uses: julia-actions/setup-julia@v1
        with:
          version: {% raw %}${{ matrix.version }}{% endraw %}
          arch: {% raw %}${{ matrix.arch }}{% endraw %}

      - name: Set up Julia caches
        uses: julia-actions/cache@v1
        with:
          cache-name: {% raw %}${{ github.repository }}-${{ github.workflow }}-${{ github.job }}-julia-${{ runner.os }}-${{ runner.arch }}-${{ matrix.version }}-${{ hashFiles('.github/workflows/CI.yml') }}{% endraw %}

      - name: Build package
        uses: julia-actions/julia-buildpkg@v1

      - name: Run tests
        uses: julia-actions/julia-runtest@v1
{% if cookiecutter.ci_include_codecov == "yes" %}
      - name: Process coverage data
        # Only run for 'main' branch running on 'Linux' with the latest version of Julia
        if: |
            github.ref_name == 'main' &&
            runner.os == env.codecov-os &&
            matrix.arch == env.codecov-arch &&
            matrix.version == env.codecov-version

        uses: julia-actions/julia-processcoverage@v1
        with:
          directories: src

      - name: Upload code coverage data to codecov.io
        # Only run for 'main' branch running on 'Linux' with the latest version of Julia
        if: |
            github.ref_name == 'main' &&
            runner.os == env.codecov-os &&
            matrix.arch == env.codecov-arch &&
            matrix.version == env.codecov-version

        uses: codecov/codecov-action@v3
        with:
          token: {% raw %}${{ secrets.CODECOV_TOKEN }}{% endraw %}
          files: lcov.info
          fail_ci_if_error: true
          verbose: true
{% endif %}
{% if cookiecutter.enable_github_pages == "yes" %}
  build-docs:
    name: Build Documentation

    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Julia environment
        uses: julia-actions/setup-julia@latest
        with:
          version: '1.9'

      - name: Install dependencies
        run: julia --project=docs --color=yes -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'

      - name: Build and deploy documentation
        run: julia --project=docs --color=yes --compile=min -O0 docs/make.jl
        env:
          GITHUB_TOKEN: {% raw %}${{ secrets.GITHUB_TOKEN }}{% endraw %}
          DOCUMENTER_KEY: {% raw %}${{ secrets.DOCUMENTER_KEY }}{% endraw %}
{% endif %}
